Update release_branches.yml

diff --git a/.github/workflows/release_branches.yml b/.github/workflows/release_branches.yml
--- a/.github/workflows/release_branches.yml
+++ b/.github/workflows/release_branches.yml
@@ -178,7 +178,7 @@ jobs:
           sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
   BuilderDebAarch64:
     needs: [DockerHubPush]
-    runs-on: [self-hosted, builder-aarch64, altinity-aarch64]
+    runs-on: [self-hosted, builder, on-demand, type-cax41, image-arm-app-docker-ce]
     steps:
       - name: Set envs
         run: |
@@ -394,7 +394,7 @@ jobs:
 
   FunctionalStatelessTestAarch64:
     needs: [BuilderDebAarch64]
-    runs-on: [self-hosted, func-tester-aarch64, altinity-aarch64]
+    runs-on: [self-hosted, func-tester, on-demand, type-cax41, image-arm-snapshot-docker_ipv6_arm]
     steps:
       - name: Setup
         run: |
@@ -483,7 +483,7 @@ jobs:
           sudo rm -fr "$TEMP_PATH"
   FunctionalStatefulTestAarch64:
     needs: [BuilderDebAarch64]
-    runs-on: [self-hosted, func-tester-aarch64, altinity-aarch64]
+    runs-on: [self-hosted, func-tester, on-demand, type-cax41, image-arm-snapshot-docker_ipv6_arm]
     steps:
       - name: Setup
         run: |
@@ -532,80 +532,80 @@ jobs:
 #############################################################################################
 ############################# INTEGRATION TESTS #############################################
 #############################################################################################
-  IntegrationTestsRelease0:
-    needs: [BuilderDebRelease]
-    runs-on: [self-hosted, stress-tester, on-demand, type-ccx52]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/integration_tests_release
-          REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Integration tests (release)
-          REPO_COPY=${{runner.temp}}/integration_tests_release/ClickHouse
-          RUN_BY_HASH_NUM=0
-          RUN_BY_HASH_TOTAL=2
-          EOF
-      - name: Download json reports
-        uses: actions/download-artifact@v3
-        with:
-          path: ${{ env.REPORTS_PATH }}
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-      - name: Integration test
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci"
-          python3 integration_test_check.py "$CHECK_NAME"
-      - name: Cleanup
-        if: always()
-        run: |
-          # shellcheck disable=SC2046
-          docker kill $(docker ps -q) ||:
-          # shellcheck disable=SC2046
-          docker rm -f $(docker ps -a -q) ||:
-          sudo rm -fr "$TEMP_PATH"
-  IntegrationTestsRelease1:
-    needs: [BuilderDebRelease]
-    runs-on: [self-hosted, stress-tester, on-demand, type-ccx52]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/integration_tests_release
-          REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Integration tests (release)
-          REPO_COPY=${{runner.temp}}/integration_tests_release/ClickHouse
-          RUN_BY_HASH_NUM=1
-          RUN_BY_HASH_TOTAL=2
-          EOF
-      - name: Download json reports
-        uses: actions/download-artifact@v3
-        with:
-          path: ${{ env.REPORTS_PATH }}
-      - name: Check out repository code
-        uses: ClickHouse/checkout@v1
-        with:
-          clear-repository: true
-      - name: Integration test
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci"
-          python3 integration_test_check.py "$CHECK_NAME"
-      - name: Cleanup
-        if: always()
-        run: |
-          # shellcheck disable=SC2046
-          docker kill $(docker ps -q) ||:
-          # shellcheck disable=SC2046
-          docker rm -f $(docker ps -a -q) ||:
-          sudo rm -fr "$TEMP_PATH"
+  # IntegrationTestsRelease0:
+  #   needs: [BuilderDebRelease]
+  #   runs-on: [self-hosted, stress-tester, on-demand, type-ccx52]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/integration_tests_release
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Integration tests (release)
+  #         REPO_COPY=${{runner.temp}}/integration_tests_release/ClickHouse
+  #         RUN_BY_HASH_NUM=0
+  #         RUN_BY_HASH_TOTAL=2
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #     - name: Integration test
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 integration_test_check.py "$CHECK_NAME"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         # shellcheck disable=SC2046
+  #         docker kill $(docker ps -q) ||:
+  #         # shellcheck disable=SC2046
+  #         docker rm -f $(docker ps -a -q) ||:
+  #         sudo rm -fr "$TEMP_PATH"
+  # IntegrationTestsRelease1:
+  #   needs: [BuilderDebRelease]
+  #   runs-on: [self-hosted, stress-tester, on-demand, type-ccx52]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/integration_tests_release
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Integration tests (release)
+  #         REPO_COPY=${{runner.temp}}/integration_tests_release/ClickHouse
+  #         RUN_BY_HASH_NUM=1
+  #         RUN_BY_HASH_TOTAL=2
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Check out repository code
+  #       uses: ClickHouse/checkout@v1
+  #       with:
+  #         clear-repository: true
+  #     - name: Integration test
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 integration_test_check.py "$CHECK_NAME"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         # shellcheck disable=SC2046
+  #         docker kill $(docker ps -q) ||:
+  #         # shellcheck disable=SC2046
+  #         docker rm -f $(docker ps -a -q) ||:
+  #         sudo rm -fr "$TEMP_PATH"
 #############################################################################################
 ##################################### REGRESSION TESTS ######################################
 #############################################################################################
