Removing FastTest, UpgradeCheck, and Jepsen

diff --git a/.github/workflows/release_branches.yml b/.github/workflows/release_branches.yml
--- a/.github/workflows/release_branches.yml
+++ b/.github/workflows/release_branches.yml
@@ -122,36 +122,6 @@ jobs:
           docker ps --quiet | xargs --no-run-if-empty docker kill ||:
           docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
           sudo rm -fr "$TEMP_PATH"
-  FastTest:
-    needs: DockerHubPush
-    runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx51, altinity-in-ash, altinity-image-x86-app-docker-ce]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/fasttest
-          REPO_COPY=${{runner.temp}}/fasttest/ClickHouse
-          CACHES_PATH=${{runner.temp}}/../ccaches
-          EOF
-      - name: Check out repository code
-        uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
-        with:
-          clear-repository: true
-      - name: Download changed images
-        uses: actions/download-artifact@v3
-        with:
-          name: changed_images
-          path: ${{ env.TEMP_PATH }}
-      - name: Fast Test
-        run: |
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci" && python3 fast_test_check.py
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH" "$CACHES_PATH"
   CompatibilityCheckX86:
     needs: [BuilderDebRelease]
     runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx41, altinity-in-ash, altinity-image-x86-app-docker-ce]
@@ -2960,139 +2930,139 @@ jobs:
   ##############################################################################################
   ######################################### UPGRADE CHECK ######################################
   ##############################################################################################
-  UpgradeCheckAsan:
-    needs: [BuilderDebAsan]
-    runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx51, altinity-in-ash, altinity-image-x86-app-docker-ce]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/upgrade_asan
-          REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Upgrade check (asan)
-          REPO_COPY=${{runner.temp}}/upgrade_asan/ClickHouse
-          EOF
-      - name: Download json reports
-        uses: actions/download-artifact@v3
-        with:
-          path: ${{ env.REPORTS_PATH }}
-      - name: Check out repository code
-        uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
-        with:
-          clear-repository: true
-      - name: Upgrade check
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci"
-          python3 upgrade_check.py "$CHECK_NAME"
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH"
-  UpgradeCheckTsan:
-    needs: [BuilderDebTsan]
-    # same as for stress test with tsan
-    runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx51, altinity-in-ash, altinity-image-x86-app-docker-ce]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/upgrade_thread
-          REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Upgrade check (tsan)
-          REPO_COPY=${{runner.temp}}/upgrade_thread/ClickHouse
-          EOF
-      - name: Download json reports
-        uses: actions/download-artifact@v3
-        with:
-          path: ${{ env.REPORTS_PATH }}
-      - name: Check out repository code
-        uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
-        with:
-          clear-repository: true
-      - name: Upgrade check
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci"
-          python3 upgrade_check.py "$CHECK_NAME"
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH"
-  UpgradeCheckMsan:
-    needs: [BuilderDebMsan]
-    runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx51, altinity-in-ash, altinity-image-x86-app-docker-ce]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/upgrade_memory
-          REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Upgrade check (msan)
-          REPO_COPY=${{runner.temp}}/upgrade_memory/ClickHouse
-          EOF
-      - name: Download json reports
-        uses: actions/download-artifact@v3
-        with:
-          path: ${{ env.REPORTS_PATH }}
-      - name: Check out repository code
-        uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
-        with:
-          clear-repository: true
-      - name: Upgrade check
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci"
-          python3 upgrade_check.py "$CHECK_NAME"
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH"
-  UpgradeCheckDebug:
-    needs: [BuilderDebDebug]
-    runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx51, altinity-in-ash, altinity-image-x86-app-docker-ce]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/upgrade_debug
-          REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Upgrade check (debug)
-          REPO_COPY=${{runner.temp}}/upgrade_debug/ClickHouse
-          EOF
-      - name: Download json reports
-        uses: actions/download-artifact@v3
-        with:
-          path: ${{ env.REPORTS_PATH }}
-      - name: Check out repository code
-        uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
-        with:
-          clear-repository: true
-      - name: Upgrade check
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci"
-          python3 upgrade_check.py "$CHECK_NAME"
-      - name: Cleanup
-        if: always()
-        run: |
-          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
-          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
-          sudo rm -fr "$TEMP_PATH"
+  # UpgradeCheckAsan:
+  #   needs: [BuilderDebAsan]
+  #   runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx51, altinity-in-ash, altinity-image-x86-app-docker-ce]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/upgrade_asan
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Upgrade check (asan)
+  #         REPO_COPY=${{runner.temp}}/upgrade_asan/ClickHouse
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Check out repository code
+  #       uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
+  #       with:
+  #         clear-repository: true
+  #     - name: Upgrade check
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 upgrade_check.py "$CHECK_NAME"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH"
+  # UpgradeCheckTsan:
+  #   needs: [BuilderDebTsan]
+  #   # same as for stress test with tsan
+  #   runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx51, altinity-in-ash, altinity-image-x86-app-docker-ce]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/upgrade_thread
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Upgrade check (tsan)
+  #         REPO_COPY=${{runner.temp}}/upgrade_thread/ClickHouse
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Check out repository code
+  #       uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
+  #       with:
+  #         clear-repository: true
+  #     - name: Upgrade check
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 upgrade_check.py "$CHECK_NAME"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH"
+  # UpgradeCheckMsan:
+  #   needs: [BuilderDebMsan]
+  #   runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx51, altinity-in-ash, altinity-image-x86-app-docker-ce]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/upgrade_memory
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Upgrade check (msan)
+  #         REPO_COPY=${{runner.temp}}/upgrade_memory/ClickHouse
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Check out repository code
+  #       uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
+  #       with:
+  #         clear-repository: true
+  #     - name: Upgrade check
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 upgrade_check.py "$CHECK_NAME"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH"
+  # UpgradeCheckDebug:
+  #   needs: [BuilderDebDebug]
+  #   runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx51, altinity-in-ash, altinity-image-x86-app-docker-ce]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/upgrade_debug
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Upgrade check (debug)
+  #         REPO_COPY=${{runner.temp}}/upgrade_debug/ClickHouse
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Check out repository code
+  #       uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
+  #       with:
+  #         clear-repository: true
+  #     - name: Upgrade check
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 upgrade_check.py "$CHECK_NAME"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH"
 ##############################################################################################
 ##################################### AST FUZZERS ############################################
 ##############################################################################################
@@ -4097,12 +4067,9 @@ jobs:
 #############################################################################################
 ###################################### JEPSEN TESTS #########################################
 #############################################################################################
-  Jepsen:
-    # This is special test NOT INCLUDED in FinishCheck
-    # When it's skipped, all dependent tasks will be skipped too.
-    # DO NOT add it there
-    needs: [BuilderBinRelease]
-    uses: ./.github/workflows/jepsen.yml
+#   Jepsen:
+#     needs: [BuilderBinRelease]
+#     uses: ./.github/workflows/jepsen.yml
 #############################################################################################
 ##################################### REGRESSION TESTS ######################################
 #############################################################################################
@@ -5288,7 +5255,6 @@ jobs:
       - DockerHubPush
       - DockerServerImages
       - BuilderReport
-      - FastTest
       - MarkReleaseReady
       - FunctionalStatelessTestDebug0
       - FunctionalStatelessTestDebug1
