Starting to work on adding TestFlows stage.

diff --git a/.github/workflows/release_branches.yml b/.github/workflows/release_branches.yml
--- a/.github/workflows/release_branches.yml
+++ b/.github/workflows/release_branches.yml
@@ -8,7 +8,8 @@ on: # yamllint disable-line rule:truthy
   push:
     branches:
       # Anything/22.3 (e.g customizations/22.3)
-      - '**/22.3'
+      #- '**/22.3'
+      - '**/ci-enable-testflows'
 
 jobs:
   DockerHubPushAarch64:
@@ -192,95 +193,168 @@ jobs:
 ##############################################################################################
 ########################### FUNCTIONAl STATELESS TESTS #######################################
 ##############################################################################################
-  FunctionalStatelessTestRelease:
-    needs: [BuilderDebRelease]
-    runs-on: [self-hosted, func-tester]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/stateless_debug
-          REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Stateless tests (release, actions)
-          REPO_COPY=${{runner.temp}}/stateless_debug/ClickHouse
-          KILL_TIMEOUT=10800
-          EOF
-      - name: Download json reports
-        uses: actions/download-artifact@v2
-        with:
-          path: ${{ env.REPORTS_PATH }}
-      - name: Clear repository
-        run: |
-          sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
-      - name: Check out repository code
-        uses: actions/checkout@v2
-      - name: Functional test
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci"
-          python3 functional_test_check.py "$CHECK_NAME" "$KILL_TIMEOUT"
-      - name: Cleanup
-        if: always()
-        run: |
-          docker kill "$(docker ps -q)" ||:
-          docker rm -f "$(docker ps -a -q)" ||:
-          sudo rm -fr "$TEMP_PATH"
+  # FunctionalStatelessTestRelease:
+  #   needs: [BuilderDebRelease]
+  #   runs-on: [self-hosted, func-tester]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/stateless_debug
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Stateless tests (release, actions)
+  #         REPO_COPY=${{runner.temp}}/stateless_debug/ClickHouse
+  #         KILL_TIMEOUT=10800
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Clear repository
+  #       run: |
+  #         sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v2
+  #     - name: Functional test
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 functional_test_check.py "$CHECK_NAME" "$KILL_TIMEOUT"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker kill "$(docker ps -q)" ||:
+  #         docker rm -f "$(docker ps -a -q)" ||:
+  #         sudo rm -fr "$TEMP_PATH"
 ##############################################################################################
 ############################ FUNCTIONAl STATEFUL TESTS #######################################
 ##############################################################################################
-  FunctionalStatefulTestRelease:
-    needs: [BuilderDebRelease]
-    runs-on: [self-hosted, func-tester]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/stateful_debug
-          REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Stateful tests (release, actions)
-          REPO_COPY=${{runner.temp}}/stateful_debug/ClickHouse
-          KILL_TIMEOUT=3600
-          EOF
-      - name: Download json reports
-        uses: actions/download-artifact@v2
-        with:
-          path: ${{ env.REPORTS_PATH }}
-      - name: Clear repository
-        run: |
-          sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
-      - name: Check out repository code
-        uses: actions/checkout@v2
-      - name: Functional test
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci"
-          python3 functional_test_check.py "$CHECK_NAME" "$KILL_TIMEOUT"
-      - name: Cleanup
-        if: always()
-        run: |
-          docker kill "$(docker ps -q)" ||:
-          docker rm -f "$(docker ps -a -q)" ||:
-          sudo rm -fr "$TEMP_PATH"
+  # FunctionalStatefulTestRelease:
+  #   needs: [BuilderDebRelease]
+  #   runs-on: [self-hosted, func-tester]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/stateful_debug
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Stateful tests (release, actions)
+  #         REPO_COPY=${{runner.temp}}/stateful_debug/ClickHouse
+  #         KILL_TIMEOUT=3600
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Clear repository
+  #       run: |
+  #         sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v2
+  #     - name: Functional test
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 functional_test_check.py "$CHECK_NAME" "$KILL_TIMEOUT"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker kill "$(docker ps -q)" ||:
+  #         docker rm -f "$(docker ps -a -q)" ||:
+  #         sudo rm -fr "$TEMP_PATH"
 #############################################################################################
 ############################# INTEGRATION TESTS #############################################
 #############################################################################################
-  IntegrationTestsRelease0:
+  # IntegrationTestsRelease0:
+  #   needs: [BuilderDebRelease]
+  #   runs-on: [self-hosted, stress-tester]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/integration_tests_release
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Integration tests (release, actions)
+  #         REPO_COPY=${{runner.temp}}/integration_tests_release/ClickHouse
+  #         RUN_BY_HASH_NUM=0
+  #         RUN_BY_HASH_TOTAL=2
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Clear repository
+  #       run: |
+  #         sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v2
+  #     - name: Integration test
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 integration_test_check.py "$CHECK_NAME"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker kill "$(docker ps -q)" ||:
+  #         docker rm -f "$(docker ps -a -q)" ||:
+  #         sudo rm -fr "$TEMP_PATH"
+  # IntegrationTestsRelease1:
+  #   needs: [BuilderDebRelease]
+  #   runs-on: [self-hosted, stress-tester]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/integration_tests_release
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Integration tests (release, actions)
+  #         REPO_COPY=${{runner.temp}}/integration_tests_release/ClickHouse
+  #         RUN_BY_HASH_NUM=1
+  #         RUN_BY_HASH_TOTAL=2
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Clear repository
+  #       run: |
+  #         sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
+  #     - name: Check out repository code
+  #       uses: actions/checkout@v2
+  #     - name: Integration test
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 integration_test_check.py "$CHECK_NAME"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker kill "$(docker ps -q)" ||:
+  #         docker rm -f "$(docker ps -a -q)" ||:
+  #         sudo rm -fr "$TEMP_PATH"
+#############################################################################################
+################################# TESTFLOWS TESTS ###########################################
+#############################################################################################
+  TestFlowsTestsRelease:
     needs: [BuilderDebRelease]
     runs-on: [self-hosted, stress-tester]
     steps:
       - name: Set envs
         run: |
           cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/integration_tests_release
+          TEMP_PATH=${{runner.temp}}/testflows_tests_release
           REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Integration tests (release, actions)
-          REPO_COPY=${{runner.temp}}/integration_tests_release/ClickHouse
-          RUN_BY_HASH_NUM=0
-          RUN_BY_HASH_TOTAL=2
+          CHECK_NAME=TestFlows tests (release, actions)
+          REPO_COPY=${{runner.temp}}/testflows_tests_release/ClickHouse
           EOF
       - name: Download json reports
         uses: actions/download-artifact@v2
@@ -297,43 +371,7 @@ jobs:
           mkdir -p "$TEMP_PATH"
           cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
           cd "$REPO_COPY/tests/ci"
-          python3 integration_test_check.py "$CHECK_NAME"
-      - name: Cleanup
-        if: always()
-        run: |
-          docker kill "$(docker ps -q)" ||:
-          docker rm -f "$(docker ps -a -q)" ||:
-          sudo rm -fr "$TEMP_PATH"
-  IntegrationTestsRelease1:
-    needs: [BuilderDebRelease]
-    runs-on: [self-hosted, stress-tester]
-    steps:
-      - name: Set envs
-        run: |
-          cat >> "$GITHUB_ENV" << 'EOF'
-          TEMP_PATH=${{runner.temp}}/integration_tests_release
-          REPORTS_PATH=${{runner.temp}}/reports_dir
-          CHECK_NAME=Integration tests (release, actions)
-          REPO_COPY=${{runner.temp}}/integration_tests_release/ClickHouse
-          RUN_BY_HASH_NUM=1
-          RUN_BY_HASH_TOTAL=2
-          EOF
-      - name: Download json reports
-        uses: actions/download-artifact@v2
-        with:
-          path: ${{ env.REPORTS_PATH }}
-      - name: Clear repository
-        run: |
-          sudo rm -fr "$GITHUB_WORKSPACE" && mkdir "$GITHUB_WORKSPACE"
-      - name: Check out repository code
-        uses: actions/checkout@v2
-      - name: Integration test
-        run: |
-          sudo rm -fr "$TEMP_PATH"
-          mkdir -p "$TEMP_PATH"
-          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
-          cd "$REPO_COPY/tests/ci"
-          python3 integration_test_check.py "$CHECK_NAME"
+          python3 testflows_test_check.py "$CHECK_NAME"
       - name: Cleanup
         if: always()
         run: |
@@ -344,10 +382,11 @@ jobs:
     needs:
       - DockerHubPush
       - BuilderReport
-      - FunctionalStatelessTestRelease
-      - FunctionalStatefulTestRelease
-      - IntegrationTestsRelease0
-      - IntegrationTestsRelease1
+      #- FunctionalStatelessTestRelease
+      #- FunctionalStatefulTestRelease
+      #- IntegrationTestsRelease0
+      #- IntegrationTestsRelease1
+      - TestFlowsTestsRelease
       - CompatibilityCheck
     runs-on: [self-hosted, style-checker]
     steps:
