Update release_branches.yml

diff --git a/.github/workflows/release_branches.yml b/.github/workflows/release_branches.yml
--- a/.github/workflows/release_branches.yml
+++ b/.github/workflows/release_branches.yml
@@ -222,7 +222,7 @@ jobs:
     needs:
       - BuilderDebRelease
       - BuilderDebAarch64
-    runs-on: [self-hosted, style-checker, on-demand, type-cpx41, image-x86-app-docker-ce]
+    runs-on: [self-hosted, style-checker, on-demand, type-cpx51, image-x86-app-docker-ce]
     timeout-minutes: 180
     steps:
       - name: Check out repository code
@@ -250,7 +250,7 @@ jobs:
     needs:
       - BuilderDebRelease
       - BuilderDebAarch64
-    runs-on: [self-hosted, style-checker, on-demand, type-cpx41, image-x86-app-docker-ce]
+    runs-on: [self-hosted, style-checker, on-demand, type-cpx31, image-x86-app-docker-ce]
     timeout-minutes: 180
     if: ${{ success() || failure() }}
     steps:
@@ -332,7 +332,9 @@ jobs:
   #    - BuilderBinDarwinAarch64
       - BuilderDebRelease
       - BuilderDebAarch64
+      - SignRelease
     runs-on: [self-hosted, style-checker, on-demand, type-cpx31, image-x86-app-docker-ce]
+    timeout-minutes: 180
     steps:
       - name: Check out repository code
         uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
@@ -342,6 +344,96 @@ jobs:
         run: |
           cd "$GITHUB_WORKSPACE/tests/ci"
           python3 mark_release_ready.py
+############################################################################################
+#################################### INSTALL PACKAGES ######################################
+############################################################################################
+  InstallPackagesTestRelease:
+    needs: [SignRelease]
+    runs-on: [self-hosted, style-checker, on-demand, type-cpx51, image-x86-app-docker-ce]
+    timeout-minutes: 180
+    steps:
+      - name: Setup
+        run: |
+          sudo touch /etc/docker/daemon.json
+          sudo chown ubuntu:ubuntu /etc/docker/daemon.json
+          sudo cat <<EOT > /etc/docker/daemon.json
+            {
+               "ipv6": true,
+               "fixed-cidr-v6": "2001:3984:3989::/64"
+            }
+          EOT
+          sudo chown root:root /etc/docker/daemon.json
+          sudo systemctl restart docker
+      - name: Set envs
+        run: |
+          cat >> "$GITHUB_ENV" << 'EOF'
+          TEMP_PATH=${{runner.temp}}/test_install
+          REPORTS_PATH=${{runner.temp}}/reports_dir
+          CHECK_NAME=Install packages (amd64)
+          REPO_COPY=${{runner.temp}}/test_install/ClickHouse
+          EOF
+      - name: Download json reports
+        uses: actions/download-artifact@v3
+        with:
+          path: ${{ env.REPORTS_PATH }}
+      - name: Check out repository code
+        uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
+        with:
+          clear-repository: true
+      - name: Test packages installation
+        run: |
+          sudo rm -fr "$TEMP_PATH"
+          mkdir -p "$TEMP_PATH"
+          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+          cd "$REPO_COPY/tests/ci"
+          python3 install_check.py "$CHECK_NAME"
+      - name: Cleanup
+        if: always()
+        run: |
+          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+          sudo rm -fr "$TEMP_PATH"
+  # InstallPackagesTestAarch64:
+  #   needs: [BuilderDebAarch64]
+  #   runs-on: [self-hosted, style-checker-aarch64]
+  #   steps:
+  #     - name: Set envs
+  #       run: |
+  #         cat >> "$GITHUB_ENV" << 'EOF'
+  #         TEMP_PATH=${{runner.temp}}/test_install
+  #         REPORTS_PATH=${{runner.temp}}/reports_dir
+  #         CHECK_NAME=Install packages (arm64)
+  #         REPO_COPY=${{runner.temp}}/test_install/ClickHouse
+  #         EOF
+  #     - name: Download json reports
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         path: ${{ env.REPORTS_PATH }}
+  #     - name: Check out repository code
+  #       uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
+  #       with:
+  #         clear-repository: true
+  #     - name: Test packages installation
+  #       run: |
+  #         sudo rm -fr "$TEMP_PATH"
+  #         mkdir -p "$TEMP_PATH"
+  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
+  #         cd "$REPO_COPY/tests/ci"
+  #         python3 install_check.py "$CHECK_NAME"
+  #     - name: Cleanup
+  #       if: always()
+  #       run: |
+  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
+  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
+  #         sudo rm -fr "$TEMP_PATH"
+
+  tests_start:
+    ## Do-nothing stage to trigger tests, makes is easier to
+    needs: [InstallPackagesTestRelease]
+    runs-on: ubuntu-latest
+    timeout-minutes: 180
+    steps:
+      - run: true
 ##############################################################################################
 ########################### FUNCTIONAl STATELESS TESTS #######################################
 ##############################################################################################
